
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-jwt
    username: root
    password: pa55word
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  port: 8080